/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module BSA(x, y, clk, rst, s, start);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire car1;
  wire car2;
  input clk;
  wire fs;
  input rst;
  output s;
  input start;
  input x;
  input y;
  INVX8 _4_ (
    .A(car1),
    .Y(_2_)
  );
  NOR2X1 _5_ (
    .A(start),
    .B(_2_),
    .Y(_0_)
  );
  INVX8 _6_ (
    .A(fs),
    .Y(_3_)
  );
  NOR2X1 _7_ (
    .A(start),
    .B(_3_),
    .Y(_1_)
  );
  DFFSR _8_ (
    .CLK(clk),
    .D(_0_),
    .Q(car2),
    .R(rst),
    .S(1'b1)
  );
  DFFSR _9_ (
    .CLK(clk),
    .D(_1_),
    .Q(s),
    .R(rst),
    .S(1'b1)
  );
  FA fa (
    .a(x),
    .b(y),
    .c(car2),
    .cout(car1),
    .out(fs)
  );
endmodule

module BSTC(a, s, clk, rst, start);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  input clk;
  input rst;
  output s;
  input start;
  wire z;
  INVX8 _4_ (
    .A(start),
    .Y(_2_)
  );
  OAI21X1 _5_ (
    .A(z),
    .B(a),
    .C(_2_),
    .Y(_3_)
  );
  AOI21X1 _6_ (
    .A(z),
    .B(a),
    .C(_3_),
    .Y(_0_)
  );
  INVX1 _7_ (
    .A(_3_),
    .Y(_1_)
  );
  DFFSR _8_ (
    .CLK(clk),
    .D(_1_),
    .Q(z),
    .R(rst),
    .S(1'b1)
  );
  DFFSR _9_ (
    .CLK(clk),
    .D(_0_),
    .Q(s),
    .R(rst),
    .S(1'b1)
  );
endmodule

module FA(a, b, c, out, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input a;
  input b;
  input c;
  output cout;
  output out;
  NAND2X1 _07_ (
    .A(b),
    .B(a),
    .Y(_03_)
  );
  OR2X2 _08_ (
    .A(b),
    .B(a),
    .Y(_04_)
  );
  NAND3X1 _09_ (
    .A(c),
    .B(_03_),
    .C(_04_),
    .Y(_05_)
  );
  NOR2X1 _10_ (
    .A(b),
    .B(a),
    .Y(_06_)
  );
  AND2X2 _11_ (
    .A(b),
    .B(a),
    .Y(_00_)
  );
  INVX1 _12_ (
    .A(c),
    .Y(_01_)
  );
  OAI21X1 _13_ (
    .A(_06_),
    .B(_00_),
    .C(_01_),
    .Y(_02_)
  );
  AND2X1 _14_ (
    .A(_05_),
    .B(_02_),
    .Y(out)
  );
  OAI21X1 _15_ (
    .A(_01_),
    .B(_06_),
    .C(_03_),
    .Y(cout)
  );
endmodule

module SPM(MP, MC, start, P, done, clk, resetn);
  wire [63:0] _000_;
  wire _001_;
  wire _002_;
  wire [6:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  input [31:0] MC;
  input [31:0] MP;
  output [63:0] P;
  input clk;
  output done;
  wire en;
  wire [6:0] index;
  wire p;
  input resetn;
  input start;
  wire y;
  NAND2X1 _175_ (
    .A(index[3]),
    .B(index[4]),
    .Y(_006_)
  );
  INVX2 _176_ (
    .A(_006_),
    .Y(_007_)
  );
  NAND2X1 _177_ (
    .A(index[2]),
    .B(_007_),
    .Y(_008_)
  );
  NAND2X1 _178_ (
    .A(index[1]),
    .B(index[0]),
    .Y(_009_)
  );
  NOR2X1 _179_ (
    .A(en),
    .B(start),
    .Y(_010_)
  );
  NOR2X1 _180_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  INVX2 _181_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR2X1 _182_ (
    .A(_008_),
    .B(_012_),
    .Y(_013_)
  );
  NAND2X1 _183_ (
    .A(index[5]),
    .B(_013_),
    .Y(_014_)
  );
  INVX2 _184_ (
    .A(start),
    .Y(_015_)
  );
  BUFX2 _185_ (
    .A(_015_),
    .Y(_016_)
  );
  NAND2X1 _186_ (
    .A(done),
    .B(_016_),
    .Y(_017_)
  );
  OAI21X1 _187_ (
    .A(index[6]),
    .B(_014_),
    .C(_017_),
    .Y(_001_)
  );
  INVX2 _188_ (
    .A(en),
    .Y(_018_)
  );
  BUFX2 _189_ (
    .A(_018_),
    .Y(_019_)
  );
  NAND2X1 _190_ (
    .A(P[1]),
    .B(_016_),
    .Y(_020_)
  );
  NAND2X1 _191_ (
    .A(P[0]),
    .B(_010_),
    .Y(_021_)
  );
  OAI21X1 _192_ (
    .A(_019_),
    .B(_020_),
    .C(_021_),
    .Y(_000_[0])
  );
  INVX1 _193_ (
    .A(P[2]),
    .Y(_022_)
  );
  NAND2X1 _194_ (
    .A(en),
    .B(_015_),
    .Y(_023_)
  );
  BUFX2 _195_ (
    .A(_023_),
    .Y(_024_)
  );
  BUFX2 _196_ (
    .A(_024_),
    .Y(_025_)
  );
  OAI22X1 _197_ (
    .A(en),
    .B(_020_),
    .C(_022_),
    .D(_025_),
    .Y(_000_[1])
  );
  NAND2X1 _198_ (
    .A(P[3]),
    .B(_016_),
    .Y(_026_)
  );
  INVX2 _199_ (
    .A(_010_),
    .Y(_027_)
  );
  BUFX2 _200_ (
    .A(_027_),
    .Y(_028_)
  );
  OAI22X1 _201_ (
    .A(_019_),
    .B(_026_),
    .C(_022_),
    .D(_028_),
    .Y(_000_[2])
  );
  INVX1 _202_ (
    .A(P[4]),
    .Y(_029_)
  );
  OAI22X1 _203_ (
    .A(en),
    .B(_026_),
    .C(_029_),
    .D(_025_),
    .Y(_000_[3])
  );
  NAND2X1 _204_ (
    .A(P[5]),
    .B(_016_),
    .Y(_030_)
  );
  OAI22X1 _205_ (
    .A(_019_),
    .B(_030_),
    .C(_029_),
    .D(_028_),
    .Y(_000_[4])
  );
  INVX1 _206_ (
    .A(P[6]),
    .Y(_031_)
  );
  OAI22X1 _207_ (
    .A(en),
    .B(_030_),
    .C(_031_),
    .D(_025_),
    .Y(_000_[5])
  );
  NAND2X1 _208_ (
    .A(P[7]),
    .B(_016_),
    .Y(_032_)
  );
  OAI22X1 _209_ (
    .A(_019_),
    .B(_032_),
    .C(_031_),
    .D(_028_),
    .Y(_000_[6])
  );
  INVX1 _210_ (
    .A(P[8]),
    .Y(_033_)
  );
  OAI22X1 _211_ (
    .A(en),
    .B(_032_),
    .C(_033_),
    .D(_025_),
    .Y(_000_[7])
  );
  NAND2X1 _212_ (
    .A(P[9]),
    .B(_016_),
    .Y(_034_)
  );
  OAI22X1 _213_ (
    .A(_019_),
    .B(_034_),
    .C(_033_),
    .D(_028_),
    .Y(_000_[8])
  );
  INVX1 _214_ (
    .A(P[10]),
    .Y(_035_)
  );
  OAI22X1 _215_ (
    .A(en),
    .B(_034_),
    .C(_035_),
    .D(_025_),
    .Y(_000_[9])
  );
  NAND2X1 _216_ (
    .A(P[11]),
    .B(_016_),
    .Y(_036_)
  );
  OAI22X1 _217_ (
    .A(_019_),
    .B(_036_),
    .C(_035_),
    .D(_028_),
    .Y(_000_[10])
  );
  INVX1 _218_ (
    .A(P[12]),
    .Y(_037_)
  );
  OAI22X1 _219_ (
    .A(en),
    .B(_036_),
    .C(_037_),
    .D(_025_),
    .Y(_000_[11])
  );
  NAND2X1 _220_ (
    .A(P[13]),
    .B(_016_),
    .Y(_038_)
  );
  OAI22X1 _221_ (
    .A(_019_),
    .B(_038_),
    .C(_037_),
    .D(_028_),
    .Y(_000_[12])
  );
  INVX1 _222_ (
    .A(P[14]),
    .Y(_039_)
  );
  OAI22X1 _223_ (
    .A(en),
    .B(_038_),
    .C(_039_),
    .D(_025_),
    .Y(_000_[13])
  );
  NAND2X1 _224_ (
    .A(P[15]),
    .B(_016_),
    .Y(_040_)
  );
  OAI22X1 _225_ (
    .A(_019_),
    .B(_040_),
    .C(_039_),
    .D(_028_),
    .Y(_000_[14])
  );
  INVX1 _226_ (
    .A(P[16]),
    .Y(_041_)
  );
  OAI22X1 _227_ (
    .A(en),
    .B(_040_),
    .C(_041_),
    .D(_025_),
    .Y(_000_[15])
  );
  BUFX2 _228_ (
    .A(_015_),
    .Y(_042_)
  );
  NAND2X1 _229_ (
    .A(P[17]),
    .B(_042_),
    .Y(_043_)
  );
  OAI22X1 _230_ (
    .A(_019_),
    .B(_043_),
    .C(_041_),
    .D(_028_),
    .Y(_000_[16])
  );
  INVX1 _231_ (
    .A(P[18]),
    .Y(_044_)
  );
  OAI22X1 _232_ (
    .A(en),
    .B(_043_),
    .C(_044_),
    .D(_025_),
    .Y(_000_[17])
  );
  BUFX2 _233_ (
    .A(_018_),
    .Y(_045_)
  );
  NAND2X1 _234_ (
    .A(P[19]),
    .B(_042_),
    .Y(_046_)
  );
  BUFX2 _235_ (
    .A(_027_),
    .Y(_047_)
  );
  OAI22X1 _236_ (
    .A(_045_),
    .B(_046_),
    .C(_044_),
    .D(_047_),
    .Y(_000_[18])
  );
  INVX1 _237_ (
    .A(P[20]),
    .Y(_048_)
  );
  OAI22X1 _238_ (
    .A(en),
    .B(_046_),
    .C(_048_),
    .D(_025_),
    .Y(_000_[19])
  );
  NAND2X1 _239_ (
    .A(P[21]),
    .B(_042_),
    .Y(_049_)
  );
  OAI22X1 _240_ (
    .A(_045_),
    .B(_049_),
    .C(_048_),
    .D(_047_),
    .Y(_000_[20])
  );
  INVX1 _241_ (
    .A(P[22]),
    .Y(_050_)
  );
  BUFX2 _242_ (
    .A(_024_),
    .Y(_051_)
  );
  OAI22X1 _243_ (
    .A(en),
    .B(_049_),
    .C(_050_),
    .D(_051_),
    .Y(_000_[21])
  );
  NAND2X1 _244_ (
    .A(P[23]),
    .B(_042_),
    .Y(_052_)
  );
  OAI22X1 _245_ (
    .A(_045_),
    .B(_052_),
    .C(_050_),
    .D(_047_),
    .Y(_000_[22])
  );
  INVX1 _246_ (
    .A(P[24]),
    .Y(_053_)
  );
  OAI22X1 _247_ (
    .A(en),
    .B(_052_),
    .C(_053_),
    .D(_051_),
    .Y(_000_[23])
  );
  NAND2X1 _248_ (
    .A(P[25]),
    .B(_042_),
    .Y(_054_)
  );
  OAI22X1 _249_ (
    .A(_045_),
    .B(_054_),
    .C(_053_),
    .D(_047_),
    .Y(_000_[24])
  );
  INVX1 _250_ (
    .A(P[26]),
    .Y(_055_)
  );
  OAI22X1 _251_ (
    .A(en),
    .B(_054_),
    .C(_055_),
    .D(_051_),
    .Y(_000_[25])
  );
  NAND2X1 _252_ (
    .A(P[27]),
    .B(_042_),
    .Y(_056_)
  );
  OAI22X1 _253_ (
    .A(_045_),
    .B(_056_),
    .C(_055_),
    .D(_047_),
    .Y(_000_[26])
  );
  INVX1 _254_ (
    .A(P[28]),
    .Y(_057_)
  );
  OAI22X1 _255_ (
    .A(en),
    .B(_056_),
    .C(_057_),
    .D(_051_),
    .Y(_000_[27])
  );
  NAND2X1 _256_ (
    .A(P[29]),
    .B(_042_),
    .Y(_058_)
  );
  OAI22X1 _257_ (
    .A(_045_),
    .B(_058_),
    .C(_057_),
    .D(_047_),
    .Y(_000_[28])
  );
  INVX1 _258_ (
    .A(P[30]),
    .Y(_059_)
  );
  OAI22X1 _259_ (
    .A(en),
    .B(_058_),
    .C(_059_),
    .D(_051_),
    .Y(_000_[29])
  );
  NAND2X1 _260_ (
    .A(P[31]),
    .B(_042_),
    .Y(_060_)
  );
  OAI22X1 _261_ (
    .A(_045_),
    .B(_060_),
    .C(_059_),
    .D(_047_),
    .Y(_000_[30])
  );
  INVX1 _262_ (
    .A(P[32]),
    .Y(_061_)
  );
  OAI22X1 _263_ (
    .A(en),
    .B(_060_),
    .C(_061_),
    .D(_051_),
    .Y(_000_[31])
  );
  NAND2X1 _264_ (
    .A(P[33]),
    .B(_042_),
    .Y(_062_)
  );
  OAI22X1 _265_ (
    .A(_045_),
    .B(_062_),
    .C(_061_),
    .D(_047_),
    .Y(_000_[32])
  );
  INVX1 _266_ (
    .A(P[34]),
    .Y(_063_)
  );
  OAI22X1 _267_ (
    .A(en),
    .B(_062_),
    .C(_063_),
    .D(_051_),
    .Y(_000_[33])
  );
  NAND2X1 _268_ (
    .A(P[35]),
    .B(_042_),
    .Y(_064_)
  );
  OAI22X1 _269_ (
    .A(_045_),
    .B(_064_),
    .C(_063_),
    .D(_047_),
    .Y(_000_[34])
  );
  INVX1 _270_ (
    .A(P[36]),
    .Y(_065_)
  );
  OAI22X1 _271_ (
    .A(en),
    .B(_064_),
    .C(_065_),
    .D(_051_),
    .Y(_000_[35])
  );
  BUFX2 _272_ (
    .A(_015_),
    .Y(_066_)
  );
  NAND2X1 _273_ (
    .A(P[37]),
    .B(_066_),
    .Y(_067_)
  );
  OAI22X1 _274_ (
    .A(_045_),
    .B(_067_),
    .C(_065_),
    .D(_047_),
    .Y(_000_[36])
  );
  INVX1 _275_ (
    .A(P[38]),
    .Y(_068_)
  );
  OAI22X1 _276_ (
    .A(en),
    .B(_067_),
    .C(_068_),
    .D(_051_),
    .Y(_000_[37])
  );
  BUFX2 _277_ (
    .A(_018_),
    .Y(_069_)
  );
  NAND2X1 _278_ (
    .A(P[39]),
    .B(_066_),
    .Y(_070_)
  );
  BUFX2 _279_ (
    .A(_027_),
    .Y(_071_)
  );
  OAI22X1 _280_ (
    .A(_069_),
    .B(_070_),
    .C(_068_),
    .D(_071_),
    .Y(_000_[38])
  );
  INVX1 _281_ (
    .A(P[40]),
    .Y(_072_)
  );
  OAI22X1 _282_ (
    .A(en),
    .B(_070_),
    .C(_072_),
    .D(_051_),
    .Y(_000_[39])
  );
  NAND2X1 _283_ (
    .A(P[41]),
    .B(_066_),
    .Y(_073_)
  );
  OAI22X1 _284_ (
    .A(_069_),
    .B(_073_),
    .C(_072_),
    .D(_071_),
    .Y(_000_[40])
  );
  INVX1 _285_ (
    .A(P[42]),
    .Y(_074_)
  );
  BUFX2 _286_ (
    .A(_024_),
    .Y(_075_)
  );
  OAI22X1 _287_ (
    .A(en),
    .B(_073_),
    .C(_074_),
    .D(_075_),
    .Y(_000_[41])
  );
  NAND2X1 _288_ (
    .A(P[43]),
    .B(_066_),
    .Y(_076_)
  );
  OAI22X1 _289_ (
    .A(_069_),
    .B(_076_),
    .C(_074_),
    .D(_071_),
    .Y(_000_[42])
  );
  INVX1 _290_ (
    .A(P[44]),
    .Y(_077_)
  );
  OAI22X1 _291_ (
    .A(en),
    .B(_076_),
    .C(_077_),
    .D(_075_),
    .Y(_000_[43])
  );
  NAND2X1 _292_ (
    .A(P[45]),
    .B(_066_),
    .Y(_078_)
  );
  OAI22X1 _293_ (
    .A(_069_),
    .B(_078_),
    .C(_077_),
    .D(_071_),
    .Y(_000_[44])
  );
  INVX1 _294_ (
    .A(P[46]),
    .Y(_079_)
  );
  OAI22X1 _295_ (
    .A(en),
    .B(_078_),
    .C(_079_),
    .D(_075_),
    .Y(_000_[45])
  );
  NAND2X1 _296_ (
    .A(P[47]),
    .B(_066_),
    .Y(_080_)
  );
  OAI22X1 _297_ (
    .A(_069_),
    .B(_080_),
    .C(_079_),
    .D(_071_),
    .Y(_000_[46])
  );
  INVX1 _298_ (
    .A(P[48]),
    .Y(_081_)
  );
  OAI22X1 _299_ (
    .A(en),
    .B(_080_),
    .C(_081_),
    .D(_075_),
    .Y(_000_[47])
  );
  NAND2X1 _300_ (
    .A(P[49]),
    .B(_066_),
    .Y(_082_)
  );
  OAI22X1 _301_ (
    .A(_069_),
    .B(_082_),
    .C(_081_),
    .D(_071_),
    .Y(_000_[48])
  );
  INVX1 _302_ (
    .A(P[50]),
    .Y(_083_)
  );
  OAI22X1 _303_ (
    .A(en),
    .B(_082_),
    .C(_083_),
    .D(_075_),
    .Y(_000_[49])
  );
  NAND2X1 _304_ (
    .A(P[51]),
    .B(_066_),
    .Y(_084_)
  );
  OAI22X1 _305_ (
    .A(_069_),
    .B(_084_),
    .C(_083_),
    .D(_071_),
    .Y(_000_[50])
  );
  INVX1 _306_ (
    .A(P[52]),
    .Y(_085_)
  );
  OAI22X1 _307_ (
    .A(en),
    .B(_084_),
    .C(_085_),
    .D(_075_),
    .Y(_000_[51])
  );
  NAND2X1 _308_ (
    .A(P[53]),
    .B(_066_),
    .Y(_086_)
  );
  OAI22X1 _309_ (
    .A(_069_),
    .B(_086_),
    .C(_085_),
    .D(_071_),
    .Y(_000_[52])
  );
  INVX1 _310_ (
    .A(P[54]),
    .Y(_087_)
  );
  OAI22X1 _311_ (
    .A(en),
    .B(_086_),
    .C(_087_),
    .D(_075_),
    .Y(_000_[53])
  );
  NAND2X1 _312_ (
    .A(P[55]),
    .B(_066_),
    .Y(_088_)
  );
  OAI22X1 _313_ (
    .A(_069_),
    .B(_088_),
    .C(_087_),
    .D(_071_),
    .Y(_000_[54])
  );
  INVX1 _314_ (
    .A(P[56]),
    .Y(_089_)
  );
  OAI22X1 _315_ (
    .A(en),
    .B(_088_),
    .C(_089_),
    .D(_075_),
    .Y(_000_[55])
  );
  NAND2X1 _316_ (
    .A(P[57]),
    .B(_015_),
    .Y(_090_)
  );
  OAI22X1 _317_ (
    .A(_069_),
    .B(_090_),
    .C(_089_),
    .D(_071_),
    .Y(_000_[56])
  );
  INVX1 _318_ (
    .A(P[58]),
    .Y(_091_)
  );
  OAI22X1 _319_ (
    .A(en),
    .B(_090_),
    .C(_091_),
    .D(_075_),
    .Y(_000_[57])
  );
  NAND2X1 _320_ (
    .A(P[59]),
    .B(_015_),
    .Y(_092_)
  );
  OAI22X1 _321_ (
    .A(_018_),
    .B(_092_),
    .C(_091_),
    .D(_027_),
    .Y(_000_[58])
  );
  INVX1 _322_ (
    .A(P[60]),
    .Y(_093_)
  );
  OAI22X1 _323_ (
    .A(en),
    .B(_092_),
    .C(_093_),
    .D(_075_),
    .Y(_000_[59])
  );
  INVX1 _324_ (
    .A(P[61]),
    .Y(_094_)
  );
  OAI22X1 _325_ (
    .A(_094_),
    .B(_024_),
    .C(_093_),
    .D(_027_),
    .Y(_000_[60])
  );
  INVX1 _326_ (
    .A(P[62]),
    .Y(_095_)
  );
  OAI22X1 _327_ (
    .A(_095_),
    .B(_024_),
    .C(_094_),
    .D(_027_),
    .Y(_000_[61])
  );
  OAI21X1 _328_ (
    .A(en),
    .B(start),
    .C(p),
    .Y(_096_)
  );
  OAI21X1 _329_ (
    .A(_095_),
    .B(_028_),
    .C(_096_),
    .Y(_000_[62])
  );
  INVX1 _330_ (
    .A(P[63]),
    .Y(_097_)
  );
  OAI21X1 _331_ (
    .A(_097_),
    .B(_028_),
    .C(_096_),
    .Y(_000_[63])
  );
  INVX1 _332_ (
    .A(index[5]),
    .Y(_098_)
  );
  OAI21X1 _333_ (
    .A(_009_),
    .B(_008_),
    .C(_098_),
    .Y(_099_)
  );
  INVX1 _334_ (
    .A(_099_),
    .Y(_100_)
  );
  OAI21X1 _335_ (
    .A(MC[31]),
    .B(_100_),
    .C(_027_),
    .Y(_101_)
  );
  INVX2 _336_ (
    .A(index[3]),
    .Y(_102_)
  );
  INVX1 _337_ (
    .A(MC[0]),
    .Y(_103_)
  );
  NAND2X1 _338_ (
    .A(index[4]),
    .B(MC[16]),
    .Y(_104_)
  );
  OAI21X1 _339_ (
    .A(index[4]),
    .B(_103_),
    .C(_104_),
    .Y(_105_)
  );
  INVX2 _340_ (
    .A(index[2]),
    .Y(_106_)
  );
  NAND3X1 _341_ (
    .A(index[3]),
    .B(index[4]),
    .C(MC[24]),
    .Y(_107_)
  );
  INVX2 _342_ (
    .A(index[4]),
    .Y(_108_)
  );
  BUFX2 _343_ (
    .A(_108_),
    .Y(_109_)
  );
  NAND3X1 _344_ (
    .A(index[3]),
    .B(MC[8]),
    .C(_109_),
    .Y(_110_)
  );
  NAND3X1 _345_ (
    .A(_106_),
    .B(_107_),
    .C(_110_),
    .Y(_111_)
  );
  AOI21X1 _346_ (
    .A(_102_),
    .B(_105_),
    .C(_111_),
    .Y(_112_)
  );
  NAND3X1 _347_ (
    .A(index[3]),
    .B(index[4]),
    .C(MC[28]),
    .Y(_113_)
  );
  NAND3X1 _348_ (
    .A(index[3]),
    .B(MC[12]),
    .C(_109_),
    .Y(_114_)
  );
  NAND3X1 _349_ (
    .A(index[2]),
    .B(_113_),
    .C(_114_),
    .Y(_115_)
  );
  NAND2X1 _350_ (
    .A(MC[4]),
    .B(_108_),
    .Y(_116_)
  );
  NAND2X1 _351_ (
    .A(index[4]),
    .B(MC[20]),
    .Y(_117_)
  );
  AOI21X1 _352_ (
    .A(_116_),
    .B(_117_),
    .C(index[3]),
    .Y(_118_)
  );
  INVX2 _353_ (
    .A(index[1]),
    .Y(_119_)
  );
  OAI21X1 _354_ (
    .A(_115_),
    .B(_118_),
    .C(_119_),
    .Y(_120_)
  );
  INVX1 _355_ (
    .A(MC[2]),
    .Y(_121_)
  );
  NAND2X1 _356_ (
    .A(index[4]),
    .B(MC[18]),
    .Y(_122_)
  );
  OAI21X1 _357_ (
    .A(index[4]),
    .B(_121_),
    .C(_122_),
    .Y(_123_)
  );
  NAND3X1 _358_ (
    .A(index[3]),
    .B(index[4]),
    .C(MC[26]),
    .Y(_124_)
  );
  NAND3X1 _359_ (
    .A(index[3]),
    .B(MC[10]),
    .C(_109_),
    .Y(_125_)
  );
  NAND3X1 _360_ (
    .A(_106_),
    .B(_124_),
    .C(_125_),
    .Y(_126_)
  );
  AOI21X1 _361_ (
    .A(_102_),
    .B(_123_),
    .C(_126_),
    .Y(_127_)
  );
  NAND3X1 _362_ (
    .A(index[3]),
    .B(index[4]),
    .C(MC[30]),
    .Y(_128_)
  );
  NAND3X1 _363_ (
    .A(index[3]),
    .B(MC[14]),
    .C(_109_),
    .Y(_129_)
  );
  NAND3X1 _364_ (
    .A(index[2]),
    .B(_128_),
    .C(_129_),
    .Y(_130_)
  );
  NAND2X1 _365_ (
    .A(MC[6]),
    .B(_109_),
    .Y(_131_)
  );
  NAND2X1 _366_ (
    .A(index[4]),
    .B(MC[22]),
    .Y(_132_)
  );
  AOI21X1 _367_ (
    .A(_131_),
    .B(_132_),
    .C(index[3]),
    .Y(_133_)
  );
  OAI21X1 _368_ (
    .A(_130_),
    .B(_133_),
    .C(index[1]),
    .Y(_134_)
  );
  OAI22X1 _369_ (
    .A(_112_),
    .B(_120_),
    .C(_127_),
    .D(_134_),
    .Y(_135_)
  );
  INVX1 _370_ (
    .A(index[0]),
    .Y(_136_)
  );
  AOI21X1 _371_ (
    .A(_135_),
    .B(_136_),
    .C(index[5]),
    .Y(_137_)
  );
  NOR2X1 _372_ (
    .A(index[4]),
    .B(_102_),
    .Y(_138_)
  );
  INVX1 _373_ (
    .A(MC[15]),
    .Y(_139_)
  );
  MUX2X1 _374_ (
    .A(MC[23]),
    .B(MC[7]),
    .S(index[4]),
    .Y(_140_)
  );
  AOI22X1 _375_ (
    .A(_138_),
    .B(_139_),
    .C(_102_),
    .D(_140_),
    .Y(_141_)
  );
  NAND2X1 _376_ (
    .A(index[2]),
    .B(_141_),
    .Y(_142_)
  );
  NAND2X1 _377_ (
    .A(index[4]),
    .B(MC[19]),
    .Y(_143_)
  );
  NAND2X1 _378_ (
    .A(MC[3]),
    .B(_109_),
    .Y(_144_)
  );
  NAND3X1 _379_ (
    .A(_102_),
    .B(_143_),
    .C(_144_),
    .Y(_145_)
  );
  INVX1 _380_ (
    .A(MC[27]),
    .Y(_146_)
  );
  INVX1 _381_ (
    .A(MC[11]),
    .Y(_147_)
  );
  AOI22X1 _382_ (
    .A(_007_),
    .B(_146_),
    .C(_147_),
    .D(_138_),
    .Y(_148_)
  );
  NAND3X1 _383_ (
    .A(_106_),
    .B(_145_),
    .C(_148_),
    .Y(_149_)
  );
  AOI21X1 _384_ (
    .A(_142_),
    .B(_149_),
    .C(_119_),
    .Y(_150_)
  );
  INVX2 _385_ (
    .A(MC[17]),
    .Y(_151_)
  );
  AOI21X1 _386_ (
    .A(_151_),
    .B(index[4]),
    .C(index[3]),
    .Y(_152_)
  );
  OAI21X1 _387_ (
    .A(index[4]),
    .B(MC[1]),
    .C(_152_),
    .Y(_153_)
  );
  INVX1 _388_ (
    .A(MC[25]),
    .Y(_154_)
  );
  OAI21X1 _389_ (
    .A(_154_),
    .B(_006_),
    .C(_106_),
    .Y(_155_)
  );
  AOI21X1 _390_ (
    .A(MC[9]),
    .B(_138_),
    .C(_155_),
    .Y(_156_)
  );
  NAND3X1 _391_ (
    .A(index[3]),
    .B(index[4]),
    .C(MC[29]),
    .Y(_157_)
  );
  NAND3X1 _392_ (
    .A(index[3]),
    .B(MC[13]),
    .C(_109_),
    .Y(_158_)
  );
  NAND3X1 _393_ (
    .A(index[2]),
    .B(_157_),
    .C(_158_),
    .Y(_159_)
  );
  INVX1 _394_ (
    .A(MC[5]),
    .Y(_160_)
  );
  OAI21X1 _395_ (
    .A(MC[21]),
    .B(_109_),
    .C(_102_),
    .Y(_161_)
  );
  AOI21X1 _396_ (
    .A(_109_),
    .B(_160_),
    .C(_161_),
    .Y(_162_)
  );
  OAI21X1 _397_ (
    .A(_159_),
    .B(_162_),
    .C(_119_),
    .Y(_163_)
  );
  AOI21X1 _398_ (
    .A(_153_),
    .B(_156_),
    .C(_163_),
    .Y(_164_)
  );
  OAI21X1 _399_ (
    .A(_150_),
    .B(_164_),
    .C(index[0]),
    .Y(_165_)
  );
  AND2X1 _400_ (
    .A(_137_),
    .B(_165_),
    .Y(_166_)
  );
  NAND2X1 _401_ (
    .A(y),
    .B(_010_),
    .Y(_167_)
  );
  OAI21X1 _402_ (
    .A(_101_),
    .B(_166_),
    .C(_167_),
    .Y(_004_)
  );
  XNOR2X1 _403_ (
    .A(_010_),
    .B(index[0]),
    .Y(_003_[0])
  );
  OAI21X1 _404_ (
    .A(_136_),
    .B(_010_),
    .C(_119_),
    .Y(_168_)
  );
  AND2X1 _405_ (
    .A(_012_),
    .B(_168_),
    .Y(_003_[1])
  );
  NOR2X1 _406_ (
    .A(index[2]),
    .B(_011_),
    .Y(_169_)
  );
  NAND2X1 _407_ (
    .A(index[2]),
    .B(_011_),
    .Y(_170_)
  );
  INVX2 _408_ (
    .A(_170_),
    .Y(_171_)
  );
  NOR2X1 _409_ (
    .A(_169_),
    .B(_171_),
    .Y(_003_[2])
  );
  NAND2X1 _410_ (
    .A(index[3]),
    .B(_171_),
    .Y(_172_)
  );
  OAI21X1 _411_ (
    .A(_106_),
    .B(_012_),
    .C(_102_),
    .Y(_173_)
  );
  AND2X1 _412_ (
    .A(_172_),
    .B(_173_),
    .Y(_003_[3])
  );
  AOI21X1 _413_ (
    .A(_172_),
    .B(_109_),
    .C(_013_),
    .Y(_003_[4])
  );
  OAI21X1 _414_ (
    .A(_008_),
    .B(_012_),
    .C(_098_),
    .Y(_174_)
  );
  AND2X1 _415_ (
    .A(_014_),
    .B(_174_),
    .Y(_003_[5])
  );
  XNOR2X1 _416_ (
    .A(_014_),
    .B(index[6]),
    .Y(_003_[6])
  );
  OAI21X1 _417_ (
    .A(done),
    .B(_019_),
    .C(_016_),
    .Y(_002_)
  );
  OR2X2 _418_ (
    .A(start),
    .B(resetn),
    .Y(_005_)
  );
  DFFPOSX1 _419_ (
    .CLK(clk),
    .D(_004_),
    .Q(y)
  );
  DFFSR _420_ (
    .CLK(clk),
    .D(_002_),
    .Q(en),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _421_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(index[0]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _422_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(index[1]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _423_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(index[2]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _424_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(index[3]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _425_ (
    .CLK(clk),
    .D(_003_[4]),
    .Q(index[4]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _426_ (
    .CLK(clk),
    .D(_003_[5]),
    .Q(index[5]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _427_ (
    .CLK(clk),
    .D(_003_[6]),
    .Q(index[6]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _428_ (
    .CLK(clk),
    .D(_001_),
    .Q(done),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _429_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(P[0]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _430_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(P[1]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _431_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(P[2]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _432_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(P[3]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _433_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(P[4]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _434_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(P[5]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _435_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(P[6]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _436_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(P[7]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _437_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(P[8]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _438_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(P[9]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _439_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(P[10]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _440_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(P[11]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _441_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(P[12]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _442_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(P[13]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _443_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(P[14]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _444_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(P[15]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _445_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(P[16]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _446_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(P[17]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _447_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(P[18]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _448_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(P[19]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _449_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(P[20]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _450_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(P[21]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _451_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(P[22]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _452_ (
    .CLK(clk),
    .D(_000_[23]),
    .Q(P[23]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _453_ (
    .CLK(clk),
    .D(_000_[24]),
    .Q(P[24]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _454_ (
    .CLK(clk),
    .D(_000_[25]),
    .Q(P[25]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _455_ (
    .CLK(clk),
    .D(_000_[26]),
    .Q(P[26]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _456_ (
    .CLK(clk),
    .D(_000_[27]),
    .Q(P[27]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _457_ (
    .CLK(clk),
    .D(_000_[28]),
    .Q(P[28]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _458_ (
    .CLK(clk),
    .D(_000_[29]),
    .Q(P[29]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _459_ (
    .CLK(clk),
    .D(_000_[30]),
    .Q(P[30]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _460_ (
    .CLK(clk),
    .D(_000_[31]),
    .Q(P[31]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _461_ (
    .CLK(clk),
    .D(_000_[32]),
    .Q(P[32]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _462_ (
    .CLK(clk),
    .D(_000_[33]),
    .Q(P[33]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _463_ (
    .CLK(clk),
    .D(_000_[34]),
    .Q(P[34]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _464_ (
    .CLK(clk),
    .D(_000_[35]),
    .Q(P[35]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _465_ (
    .CLK(clk),
    .D(_000_[36]),
    .Q(P[36]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _466_ (
    .CLK(clk),
    .D(_000_[37]),
    .Q(P[37]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _467_ (
    .CLK(clk),
    .D(_000_[38]),
    .Q(P[38]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _468_ (
    .CLK(clk),
    .D(_000_[39]),
    .Q(P[39]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _469_ (
    .CLK(clk),
    .D(_000_[40]),
    .Q(P[40]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _470_ (
    .CLK(clk),
    .D(_000_[41]),
    .Q(P[41]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _471_ (
    .CLK(clk),
    .D(_000_[42]),
    .Q(P[42]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _472_ (
    .CLK(clk),
    .D(_000_[43]),
    .Q(P[43]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _473_ (
    .CLK(clk),
    .D(_000_[44]),
    .Q(P[44]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _474_ (
    .CLK(clk),
    .D(_000_[45]),
    .Q(P[45]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _475_ (
    .CLK(clk),
    .D(_000_[46]),
    .Q(P[46]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _476_ (
    .CLK(clk),
    .D(_000_[47]),
    .Q(P[47]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _477_ (
    .CLK(clk),
    .D(_000_[48]),
    .Q(P[48]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _478_ (
    .CLK(clk),
    .D(_000_[49]),
    .Q(P[49]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _479_ (
    .CLK(clk),
    .D(_000_[50]),
    .Q(P[50]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _480_ (
    .CLK(clk),
    .D(_000_[51]),
    .Q(P[51]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _481_ (
    .CLK(clk),
    .D(_000_[52]),
    .Q(P[52]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _482_ (
    .CLK(clk),
    .D(_000_[53]),
    .Q(P[53]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _483_ (
    .CLK(clk),
    .D(_000_[54]),
    .Q(P[54]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _484_ (
    .CLK(clk),
    .D(_000_[55]),
    .Q(P[55]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _485_ (
    .CLK(clk),
    .D(_000_[56]),
    .Q(P[56]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _486_ (
    .CLK(clk),
    .D(_000_[57]),
    .Q(P[57]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _487_ (
    .CLK(clk),
    .D(_000_[58]),
    .Q(P[58]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _488_ (
    .CLK(clk),
    .D(_000_[59]),
    .Q(P[59]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _489_ (
    .CLK(clk),
    .D(_000_[60]),
    .Q(P[60]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _490_ (
    .CLK(clk),
    .D(_000_[61]),
    .Q(P[61]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _491_ (
    .CLK(clk),
    .D(_000_[62]),
    .Q(P[62]),
    .R(resetn),
    .S(1'b1)
  );
  DFFSR _492_ (
    .CLK(clk),
    .D(_000_[63]),
    .Q(P[63]),
    .R(resetn),
    .S(1'b1)
  );
  SPM32 bitX (
    .clk(clk),
    .p(p),
    .rst(_005_),
    .start(start),
    .x(MP),
    .y(y)
  );
endmodule

module SPM32(x, y, p, clk, rst, start);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input clk;
  output p;
  input rst;
  wire [31:0] s;
  input start;
  input [31:0] x;
  input y;
  AND2X1 _32_ (
    .A(y),
    .B(x[31]),
    .Y(_05_)
  );
  AND2X1 _33_ (
    .A(y),
    .B(x[0]),
    .Y(_16_)
  );
  AND2X1 _34_ (
    .A(y),
    .B(x[1]),
    .Y(_27_)
  );
  AND2X1 _35_ (
    .A(y),
    .B(x[2]),
    .Y(_31_)
  );
  AND2X1 _36_ (
    .A(y),
    .B(x[3]),
    .Y(_00_)
  );
  AND2X1 _37_ (
    .A(y),
    .B(x[4]),
    .Y(_01_)
  );
  AND2X1 _38_ (
    .A(y),
    .B(x[5]),
    .Y(_02_)
  );
  AND2X1 _39_ (
    .A(y),
    .B(x[6]),
    .Y(_03_)
  );
  AND2X1 _40_ (
    .A(y),
    .B(x[7]),
    .Y(_04_)
  );
  AND2X1 _41_ (
    .A(y),
    .B(x[8]),
    .Y(_06_)
  );
  AND2X1 _42_ (
    .A(y),
    .B(x[9]),
    .Y(_07_)
  );
  AND2X1 _43_ (
    .A(y),
    .B(x[10]),
    .Y(_08_)
  );
  AND2X1 _44_ (
    .A(y),
    .B(x[11]),
    .Y(_09_)
  );
  AND2X1 _45_ (
    .A(y),
    .B(x[12]),
    .Y(_10_)
  );
  AND2X1 _46_ (
    .A(y),
    .B(x[13]),
    .Y(_11_)
  );
  AND2X1 _47_ (
    .A(y),
    .B(x[14]),
    .Y(_12_)
  );
  AND2X1 _48_ (
    .A(y),
    .B(x[15]),
    .Y(_13_)
  );
  AND2X1 _49_ (
    .A(y),
    .B(x[16]),
    .Y(_14_)
  );
  AND2X1 _50_ (
    .A(y),
    .B(x[17]),
    .Y(_15_)
  );
  AND2X1 _51_ (
    .A(y),
    .B(x[18]),
    .Y(_17_)
  );
  AND2X1 _52_ (
    .A(y),
    .B(x[19]),
    .Y(_18_)
  );
  AND2X1 _53_ (
    .A(y),
    .B(x[20]),
    .Y(_19_)
  );
  AND2X1 _54_ (
    .A(y),
    .B(x[21]),
    .Y(_20_)
  );
  AND2X1 _55_ (
    .A(y),
    .B(x[22]),
    .Y(_21_)
  );
  AND2X1 _56_ (
    .A(y),
    .B(x[23]),
    .Y(_22_)
  );
  AND2X1 _57_ (
    .A(y),
    .B(x[24]),
    .Y(_23_)
  );
  AND2X1 _58_ (
    .A(y),
    .B(x[25]),
    .Y(_24_)
  );
  AND2X1 _59_ (
    .A(y),
    .B(x[26]),
    .Y(_25_)
  );
  AND2X1 _60_ (
    .A(y),
    .B(x[27]),
    .Y(_26_)
  );
  AND2X1 _61_ (
    .A(y),
    .B(x[28]),
    .Y(_28_)
  );
  AND2X1 _62_ (
    .A(y),
    .B(x[29]),
    .Y(_29_)
  );
  AND2X1 _63_ (
    .A(y),
    .B(x[30]),
    .Y(_30_)
  );
  BSA \addbit[0].csa  (
    .clk(clk),
    .rst(rst),
    .s(p),
    .start(start),
    .x(_16_),
    .y(s[1])
  );
  BSA \addbit[10].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[10]),
    .start(start),
    .x(_08_),
    .y(s[11])
  );
  BSA \addbit[11].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[11]),
    .start(start),
    .x(_09_),
    .y(s[12])
  );
  BSA \addbit[12].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[12]),
    .start(start),
    .x(_10_),
    .y(s[13])
  );
  BSA \addbit[13].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[13]),
    .start(start),
    .x(_11_),
    .y(s[14])
  );
  BSA \addbit[14].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[14]),
    .start(start),
    .x(_12_),
    .y(s[15])
  );
  BSA \addbit[15].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[15]),
    .start(start),
    .x(_13_),
    .y(s[16])
  );
  BSA \addbit[16].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[16]),
    .start(start),
    .x(_14_),
    .y(s[17])
  );
  BSA \addbit[17].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[17]),
    .start(start),
    .x(_15_),
    .y(s[18])
  );
  BSA \addbit[18].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[18]),
    .start(start),
    .x(_17_),
    .y(s[19])
  );
  BSA \addbit[19].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[19]),
    .start(start),
    .x(_18_),
    .y(s[20])
  );
  BSA \addbit[1].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[1]),
    .start(start),
    .x(_27_),
    .y(s[2])
  );
  BSA \addbit[20].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[20]),
    .start(start),
    .x(_19_),
    .y(s[21])
  );
  BSA \addbit[21].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[21]),
    .start(start),
    .x(_20_),
    .y(s[22])
  );
  BSA \addbit[22].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[22]),
    .start(start),
    .x(_21_),
    .y(s[23])
  );
  BSA \addbit[23].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[23]),
    .start(start),
    .x(_22_),
    .y(s[24])
  );
  BSA \addbit[24].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[24]),
    .start(start),
    .x(_23_),
    .y(s[25])
  );
  BSA \addbit[25].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[25]),
    .start(start),
    .x(_24_),
    .y(s[26])
  );
  BSA \addbit[26].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[26]),
    .start(start),
    .x(_25_),
    .y(s[27])
  );
  BSA \addbit[27].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[27]),
    .start(start),
    .x(_26_),
    .y(s[28])
  );
  BSA \addbit[28].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[28]),
    .start(start),
    .x(_28_),
    .y(s[29])
  );
  BSA \addbit[29].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[29]),
    .start(start),
    .x(_29_),
    .y(s[30])
  );
  BSA \addbit[2].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[2]),
    .start(start),
    .x(_31_),
    .y(s[3])
  );
  BSA \addbit[30].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[30]),
    .start(start),
    .x(_30_),
    .y(s[31])
  );
  BSA \addbit[3].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[3]),
    .start(start),
    .x(_00_),
    .y(s[4])
  );
  BSA \addbit[4].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[4]),
    .start(start),
    .x(_01_),
    .y(s[5])
  );
  BSA \addbit[5].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[5]),
    .start(start),
    .x(_02_),
    .y(s[6])
  );
  BSA \addbit[6].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[6]),
    .start(start),
    .x(_03_),
    .y(s[7])
  );
  BSA \addbit[7].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[7]),
    .start(start),
    .x(_04_),
    .y(s[8])
  );
  BSA \addbit[8].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[8]),
    .start(start),
    .x(_06_),
    .y(s[9])
  );
  BSA \addbit[9].csa  (
    .clk(clk),
    .rst(rst),
    .s(s[9]),
    .start(start),
    .x(_07_),
    .y(s[10])
  );
  BSTC tcmp (
    .a(_05_),
    .clk(clk),
    .rst(rst),
    .s(s[31]),
    .start(start)
  );
endmodule
